apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-connector
spec:
  selector:
    matchLabels:
      app: email-connector
  replicas: 3
  template:
    metadata:
      labels:
        app: email-connector
    spec:
      containers:
        - name: email-connector
          image: email-connector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10002