apiVersion: v1
kind: Service
metadata:
  name: email-connector-service
spec:
  type: NodePort
  selector:
    app: email-connector-service
  ports:
    - protocol: TCP
      port: 10002
      targetPort: 10002
      nodePort: 30002