apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-connector
spec:
  selector:
    matchLabels:
      app: email-connector
  replicas: 3
  template:
    metadata:
      labels:
        app: email-connector
    spec:
      containers:
        - name: email-connector
          image: rsharma0374/email-connector:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10002
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{
                "server": {
                  "port": 10002,
                  "address": "0.0.0.0"
                },
                "spring": {
                  "application": {
                    "name": "EMAIL-SERVICE"
                  }
                },
                "eureka": {
                  "client": {
                    "serviceUrl": {
                      "defaultZone": "http://eureka-0.eureka.default.svc.cluster.local:8761/eureka"
                    },
                    "register-with-eureka": true,
                    "fetch-registry": true
                  },
                  "instance": {
                    "prefer-ip-address": true,
                    "instanceId": "${spring.cloud.client.hostname}:${spring.application.name}:${server.port}"
                  }
                }
              }'