apiVersion: v1
kind: Service
metadata:
  name: email-connector
spec:
  selector:
    app: email-connector
  ports:
    - protocol: "TCP"
      port: 30080
      targetPort: 30080
      nodePort: 30080
  type: NodePort