apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-connector-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-connector-service
  template:
    metadata:
      labels:
        app: email-connector-service
    spec:
      containers:
        - name: email-connector-service
          image: rsharma0374/email-connector-service:latest
          ports:
            - containerPort: 10002
          volumeMounts:
            - name: infisical-secret-volume
              mountPath: /opt/configs/infisical.properties
              subPath: infisical.properties
              readOnly: true
      volumes:
        - name: infisical-secret-volume
          secret:
            secretName: infisical-secret
            items:
              - key: infisical.properties
                path: infisical.properties
