server:
  port: 10002
  address: 0.0.0.0

spring:
  application:
    name: EMAIL-SERVICE

#logging:
#  file:
#    name: /opt/logs/emailConnector/emailConnector.log

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server.service-discovery.svc.cluster.local:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true